project:
  type: website

website:
  favicon: assets/favicon.ico
  twitter-card: 
    title: "Verf체gbarkeit von Geodaten auf geodienste.ch"
    description: "Unter geodienste.ch stellen die Schweizer Kantone ihre r채umlichen Daten interessierten Personen und Organisationen zur Verf체gung. Diese Untersuchung zeigt, wie die Kantone ihre Geodaten auf geodienste.ch bereitstellen. Das Daten-Angebot wird verglichen in Bezug auf die Anzahl angebotener Datens채tze und in Bezug darauf, wie offen die Kantone den Zugriff auf ihre jeweiligen Geodaten gestalten."
    image: ./map-data-openness-completeness.png
    card-style: summary_large_image
  site-url: https://ralphstraumann.ch/monitoring-geodienste-ch
  page-footer:
    left: "&copy; Ralph Straumann"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ralphstraumann
      - icon: mastodon
        href: https://mstdn.social/@rastrau
      - icon: github
        href: https://github.com/rastrau

  site-url: https://ralphstraumann.ch
  navbar:
    background: primary
    logo: assets/logo.png
    search: false

format:
  html:
    theme: lumen
    anchor-sections: true
    smooth-scroll: true
    css: styles.css
    toc: true
    email-obfuscation: javascript

editor: visual

