project:
  type: website

website:
  favicon: assets/favicon.ico
  site-url: https://ralphstraumann.ch/monitoring-geodienste-ch
  twitter-card: 
    title: "Verfügbarkeit von Geodaten auf geodienste.ch"
    description: "Unter geodienste.ch stellen die Schweizer Kantone ihre räumlichen Daten interessierten Personen und Organisationen zur Verfügung. Diese Untersuchung zeigt, wie die Kantone ihre Geodaten auf geodienste.ch bereitstellen. Das Daten-Angebot wird verglichen in Bezug auf die Anzahl angebotener Datensätze und in Bezug darauf, wie offen die Kantone den Zugriff auf ihre jeweiligen Geodaten gestalten."
    image: ./assets/titlecard.png
    card-style: summary_large_image
  open-graph:
    title: "Verfügbarkeit von Geodaten auf geodienste.ch"
    description: "Unter geodienste.ch stellen die Schweizer Kantone ihre räumlichen Daten interessierten Personen und Organisationen zur Verfügung. Diese Untersuchung zeigt, wie die Kantone ihre Geodaten auf geodienste.ch bereitstellen. Das Daten-Angebot wird verglichen in Bezug auf die Anzahl angebotener Datensätze und in Bezug darauf, wie offen die Kantone den Zugriff auf ihre jeweiligen Geodaten gestalten."
    image: ./assets/titlecard.png
    locale: de_CH
  page-footer:
    left: "&copy; Ralph Straumann"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ralphstraumann
      - icon: mastodon
        href: https://mstdn.social/@rastrau
      - icon: github
        href: https://github.com/rastrau
  navbar:
    background: primary
    logo: assets/logo.png
    search: false
    
format:
  html:
    theme: lumen
    anchor-sections: true
    smooth-scroll: true
    css: styles.css
    toc: true
    email-obfuscation: javascript
